### PR TITLE
Update Date reference

### PR DESCRIPTION
**Pull request by cristianames92**
Little refactor of the Date reference in the Readme

### CODE REVIEW

**Comment by pablog** [comment]
@cristianames92 can you merge this?

**Comment by danielaRiesgo** [comment]
@pablog CodeStats didn't report so we can't merge it. I told @nahuelwolox and he talked to Ita I think.

**Comment by pablog** [comment]
OK I'll merge it

**Comment by danielaRiesgo** [comment]
I think it was best for debugging code stats to have this open, at least I understood that from Ita.

**Comment by pablog** [comment]
Too late =(

**Pull request merged**
