### PR TITLE
Updating project

### PR DESCRIPTION
**Pull request by danielaRiesgo**
## Summary ##

* Removing RAC
* Renaming to WolmoCore instead of Core
* Improving animations demo
* Adding tests
* Migrating to XCode 9.3 (adding new requested icons as well)

### Animations Demo now
design

### CODE REVIEW

**Comment by danielaRiesgo** [comment]
Guys, do you think we should do a new release to separate that now we don't have any more RAC? Maybe with a minor change in semantic versioning.

Also, do you think is good to add the animations gif to the README? (It won't work here, but it should when merging to master because of the URL)

**Comment by woloxci** [comment]
**CodeStats metrics details:**

:x: Code Coverage (Slather): 83.78 - Minimum: 85.0
:white_check_mark: Code Quality (Swiftlint): 96.0


Click [here](http://codestats.wolox.com.ar/organizations/wolox/projects/wolmo-core-ios/branches/updating-project) for more details.

**Comment by woloxci** [comment]
**CodeStats metrics details:**

:x: Code Coverage (Slather): 84.56 - Minimum: 85.0
:white_check_mark: Code Quality (Swiftlint): 96.0


Click [here](http://codestats.wolox.com.ar/organizations/wolox/projects/wolmo-core-ios/branches/updating-project) for more details.

**Comment by woloxci** [comment]
**CodeStats metrics details:**

:white_check_mark: Code Coverage (Slather): 85.79
:white_check_mark: Code Quality (Swiftlint): 94.0


Click [here](http://codestats.wolox.com.ar/organizations/wolox/projects/wolmo-core-ios/branches/updating-project) for more details.

**Comment by danielaRiesgo** [comment]
@nahuelwolox I was goind through things because of code coverage, and found I could merge two UIImage resize funcitons. I did it, but I would like you to check if they were mergeable or not because you had made them.

**Comment by aducret** [comment]
I think we should make a new release but with a mayor bump because it is a breaking change, on this version we don't support RAC anymore.

And a gif at the readme would be nice!

**Pull request merged**
